version: '3.5'
services:

# Milvus related containers
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.11
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./milvus.yaml:/milvus/configs/milvus.yaml
      - ./volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 10s
      start_period: 60s
      timeout: 5s
      retries: 10
    ports:
      - "19530:19530"
      - "9091:9091"
    expose: 
      - "19530"
    depends_on:
      - "etcd"
      - "minio"

# Our containers for the control of milvus
  milvuscontrol:

    image: milvuscontrol_image
    environment:
      - PYTHONPATH=/code/app
    ports:
      - "8002:8001"
    build:
      context: .
    env_file:
      - .env
    expose:
      - "8002"
    container_name: milvuscontrol

    depends_on:
      standalone: 
        condition: service_healthy

  milvus-attu:
  
    image: zilliz/attu:v2.3.8
    environment:
      - MILVUS_URL= standalone:19530
    ports:
      - ${ATTU_PORT}:3000
    expose:
    - ${ATTU_PORT}

    depends_on:
      standalone: 
        condition: service_healthy

  indexer:
    image: indexer_image
    ports:
      - ${INDEXER_PORT}:270
    build:
      context: .
      dockerfile: Dockerfile.indexer
    env_file:
      - .env
    expose:
      - ${INDEXER_PORT}
    container_name: indexer


networks:
  default:
    name: my_network
    external: true